Discussion/Controllers/DiscussController.cs
using Discussion.Services;
using Discussion.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Discussion.Controllers
{
    public class DiscussController : Controller
    {
        private readonly IDiscussService _discussService;
        public DiscussController(IDiscussService discussService)
        {
            _discussService = discussService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(DiscussCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _discussService.Create(model, User);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }
    }
}

Discussion/Controllers/HomeController.cs
using Discussion.Models;
using Discussion.Services;
using Discussion.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Discussion.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IDiscussService _discussService;

        public HomeController(ILogger<HomeController> logger, IDiscussService discussService)
        {
            _logger = logger;
            _discussService = discussService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            int pageSize = 12;

            var discs = await _discussService.GetAllDiscussions();
            var count = discs.Count;
            var items = discs.Skip((page - 1) * pageSize).Take(pageSize).ToList();

            PageViewModel pageViewModel = new PageViewModel(count, page, pageSize);
            IndexViewModel viewModel = new IndexViewModel
            {
                PageViewModel = pageViewModel,
                Discussions = items
            };
            return View(viewModel);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Discussion/Views/Home/Index.cshtml
@using Discussion.ViewModels
@model IndexViewModel
@addTagHelper *, Discussion

@{
    ViewData["Title"] = "Discussion";
}

<div class="container-fluid">
    <img src="files/hitsdisc.png" class="d-block w-100 mt-4"/>
    <h1 class="text-center mt-3 mb-4"> Обсуждения </h1>

    <div class="row mb-2">
    <div class="col">
        @if (User.Identity.IsAuthenticated)
        {
            <a class="btn btn-dark"  asp-controller="Discuss" asp-action="Create">Создать</a>
        }
    </div>
    <div class="col">
        <page-link page-model="Model.PageViewModel" page-action="Index" ></page-link>
    </div>
</div>

 @if (Model.Discussions.Any())
        {

                @foreach (var discuss in Model.Discussions)
                {
                <div class="card mt-3">
                 <div class="card-header">
                   <div class="row no-gutters">
                    <h5 class="col">
                      @discuss.Name
                    </h5>
                    <div class="col col-md-auto">
                     Иван Иванов
                    </div>
                   </div>
                  </div>
  
                 <div>
                   <div class="card-body">
                    @discuss.Description
                   </div>
                   <div class="card-footer">
                     <div class="row no-gutters">
                       <div class="col">  12.06.2022 </div>
                       <a class="col col-md-auto text-right" href="/details.html" style="color: #343a40;"> <em> 5 комментариев</em> </a>
                     </div>
                   </div>
                 </div>
                </div>
                }

        }
        else
        {
            <div class="alert alert-info">
                Обсуждений ещё нет
            </div>
        }


</div>